name = "mornigdock"
main = "api/index.js"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

# ğŸ”¥ ì •ì  íŒŒì¼ ì„œë¹™
[assets]
directory = "./dist"
binding = "ASSETS"

# ---- D1 Database ----
[[d1_databases]]
binding = "DB"
database_name = "morningdock-db"
database_id = "60293aba-5567-4f16-a860-8ffca82e65da"

# ---- KV Namespace ----
[[kv_namespaces]]
binding = "KV"
id = "0d816f43804d400abe81df5bc45e5313"

# ---- AI Binding ----
[ai]
binding = "AI"

# ---- Build ----
[build]
command = "npm run build"

# ---- Production ----
[env.production]
workers_dev = false
