name = "mornigdock-ap"
main = "src/index.js"
compatibility_date = "2024-02-12"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "morningdock-db"
database_id = "60293aba-5567-4f16-a860-8ffca82e65da"

[[kv_namespaces]]
binding = "KV"
id = "0d816f43804d400abe81df5bc45e5313"

[ai]
binding = "AI"
