name = "mornigdock"
main = "src/index.js"
compatibility_date = "2024-02-12"

[[d1_databases]]
binding = "DB"
database_name = "morningdock-db"
database_id = "0da8b356-912b-4d40-97eb-44c13038a8e1"

[[kv_namespaces]]
binding = "KV"
id = "75470125585b4d7f8d689626b8408cf3"

[ai]
binding = "AI"
